export const colors = {
  navigation: '#121315',
  navigationHover: '#1B1D21',
  navigationActive: '#262A2F',
  canvas: '#F2F3F5',
  surface: '#FFFFFF',
  surfaceMuted: '#F9FAFB',
  border: '#E5E7EB',
  borderStrong: '#D1D5DB',
  text: '#151821',
  textSecondary: '#686D78',
  placeholder: '#959AA4',
  focus: '#52667D',
  focusRing: 'rgba(82, 102, 125, 0.18)',
  success: '#166534',
  successSurface: '#ECFDF3',
  warning: '#9A5B00',
  warningSurface: '#FFF7E6',
  danger: '#B42318',
  dangerSurface: '#FEF2F2',
  info: '#365978',
  infoSurface: '#EFF6FF',
  white: '#FFFFFF',
  glassLightBg: 'linear-gradient(145deg, rgba(255,255,255,.78), rgba(245,247,249,.58))',
  glassDarkBg: 'linear-gradient(145deg, rgba(39,41,46,.86), rgba(20,22,26,.78))',
  glassBorderLight: 'rgba(255,255,255,.76)',
  glassBorderDark: 'rgba(255,255,255,.13)',
  glassShadowLight: '0 16px 40px rgba(32,38,50,.08), inset 0 1px 0 rgba(255,255,255,.92)',
  glassShadowDark: '0 24px 70px rgba(18,22,30,.20), inset 0 1px 0 rgba(255,255,255,.15), inset 1px 0 0 rgba(255,255,255,.05)'
} as const;

export const spacing = { 1: '4px', 2: '8px', 3: '12px', 4: '16px', 5: '20px', 6: '24px', 8: '32px', 10: '40px', 12: '48px' } as const;
export const radius = { xs: '8px', sm: '12px', control: '16px', card: '24px', large: '28px', xl: '32px', pill: '999px' } as const;
export const typography = { fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif', body: '14px', small: '12px', title: '32px', heading: '18px' } as const;
export const shadow = { card: '0 16px 40px rgba(25,30,40,.06)', floating: '0 18px 48px rgba(31,35,45,.12)' } as const;

export const theme = { colors, spacing, radius, typography, shadow } as const;

const cssVariables: Record<string, string> = {
  '--mc-nav': colors.navigation,
  '--mc-nav-hover': colors.navigationHover,
  '--mc-nav-active': colors.navigationActive,
  '--mc-canvas': colors.canvas,
  '--mc-surface': colors.surface,
  '--mc-surface-muted': colors.surfaceMuted,
  '--mc-border': colors.border,
  '--mc-border-strong': colors.borderStrong,
  '--mc-text': colors.text,
  '--mc-text-secondary': colors.textSecondary,
  '--mc-placeholder': colors.placeholder,
  '--mc-focus': colors.focus,
  '--mc-focus-ring': colors.focusRing,
  '--mc-success': colors.success,
  '--mc-success-surface': colors.successSurface,
  '--mc-warning': colors.warning,
  '--mc-warning-surface': colors.warningSurface,
  '--mc-danger': colors.danger,
  '--mc-danger-surface': colors.dangerSurface,
  '--mc-info': colors.info,
  '--mc-info-surface': colors.infoSurface,
  '--mc-white': colors.white,
  '--mc-glass-light-bg': colors.glassLightBg,
  '--mc-glass-dark-bg': colors.glassDarkBg,
  '--mc-glass-border-light': colors.glassBorderLight,
  '--mc-glass-border-dark': colors.glassBorderDark,
  '--mc-glass-shadow-light': colors.glassShadowLight,
  '--mc-glass-shadow-dark': colors.glassShadowDark,
  '--mc-glass-blur': '28px',
  '--mc-glass-saturation': '160%',
  '--mc-ease-apple': 'cubic-bezier(.22,1,.36,1)',
  '--mc-ease-soft': 'cubic-bezier(.2,.8,.2,1)',
  '--mc-motion-ease': 'cubic-bezier(.22,1,.36,1)',
  '--mc-space-1': spacing[1],
  '--mc-space-2': spacing[2],
  '--mc-space-3': spacing[3],
  '--mc-space-4': spacing[4],
  '--mc-space-5': spacing[5],
  '--mc-space-6': spacing[6],
  '--mc-space-8': spacing[8],
  '--mc-space-10': spacing[10],
  '--mc-space-12': spacing[12],
  '--mc-radius-xs': radius.xs,
  '--mc-radius-sm': radius.sm,
  '--mc-radius-control': radius.control,
  '--mc-radius-card': radius.card,
  '--mc-radius-large': radius.large,
  '--mc-radius-xl': radius.xl,
  '--mc-radius-pill': radius.pill,
  '--mc-font': typography.fontFamily,
  '--mc-shadow-card': shadow.card,
  '--mc-shadow-floating': shadow.floating
};

export function installTheme(): void {
  for (const [name, value] of Object.entries(cssVariables)) document.documentElement.style.setProperty(name, value);
}
